# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asuntos', '0004_asunto_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='asunto',
            name='status',
            field=models.CharField(choices=[(b'atendido', b'Atendido'), (b'no_atendido', b'No Atendido'), (b'en_proceso', b'En Proceso')], max_length=20, null=True),
        ),
    ]
