# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 16:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asuntos', '0005_asunto_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='asunto',
            name='agente_social',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asunto',
            name='status',
            field=models.CharField(blank=True, choices=[(b'atendido', b'Atendido'), (b'no_atendido', b'No Atendido'), (b'en_proceso', b'En Proceso')], max_length=20, null=True),
        ),
    ]
