# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asuntos', '0009_asunto_municipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsuntoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita_usuario', models.DateTimeField()),
                ('observaciones_cita_usuario', models.TextField(blank=True)),
                ('fecha_visita_juzgado', models.DateTimeField()),
                ('juzgado', models.CharField(max_length=100)),
                ('observaciones_visita_juzgado', models.TextField(blank=True)),
                ('asunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asuntos.Asunto')),
            ],
        ),
    ]
