# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 23:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subprocuraduria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='usuarios',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subprocuraduria',
            name='usuarios',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
